### ISSUE TITLE
Classes/namespaces don't match PSR-0

### ISSUE THREAD

**Issue by jamend** [robertmain/UniformCache#2]
The class naming scheme should be compatible with PSR-0 (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md); following these established conventions would make it much easier to integrate this library into a project since it avoids name collision issues and can be easily auto-loaded (instead of having to have a custom auto-loader or require_once).

**Comment by robertmain** [comment]
Going to use PSR-4 instead

**Comment by robertmain** [comment]
@jamend Currently in the process of rewriting using PSR-4. Stay tuned :)
